FROM golang:1.24-alpine
RUN apk add make gcc musl-dev build-base git

WORKDIR /var
COPY main.go ./
RUN go mod init main.go && go mod tidy \
    && env GOOS=wasip1 GOARCH=wasm go build -buildmode=c-shared -o main.wasm main.go