version: "3.9"
services:
  envoy:
    image: envoyproxy/envoy:v1.33.0
    ports:
      - "18000:18000"
      - "8001:8001"
    volumes:
      - ./plugins:/etc/envoy/plugins:ro
      - ./envoy.yaml:/etc/envoy/envoy.yaml:ro
    command: ["envoy", "-c", "/etc/envoy/envoy.yaml", "--log-level", "debug"]