version: "3.9"

services:
  traefik:
    image: traefik:v3.5
    container_name: traefik
    ports:
      - "80:80"
      - "8080:8080"   # dashboard
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./dynamic:/etc/traefik/dynamic:ro