entryPoints:
  web:
    address: ":80"

providers:
  file:
    directory: /etc/traefik/dynamic
    watch: true

api:
  insecure: true

experimental:
  localPlugins:
    user:
      moduleName: github.com/plugin/user